### ISSUE TITLE
Probably deadlock or failure waiting for thread to initialize.

### ISSUE THREAD

**Issue by TheNotary** [AndrewMarchukov/insurgency-sandstorm-server-dockerize#44]
Good morning, I tried running the server last night and couldn't get it past this point.  I copy/ pasted the docker-compose.yml from the hub, and then to trouble shoot manually `wget`ed the various config files from this repo to see if that would help but it didn't.  

<img width="982" alt="Screenshot 2023-10-28 at 11 14 41 AM" src="https://github.com/AndrewMarchukov/insurgency-sandstorm-server-dockerize/assets/799247/7c0bcd1e-5ca2-4333-862e-8ac6936d0b7c">

```
version: '3.7'
services:
  insurgency-sandstorm:
    image: andrewmhub/insurgency-sandstorm:latest
    container_name: insurgency-sandstorm
    restart: unless-stopped
    env_file:
       - .env
    volumes:
      - ./config/ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer:ro
      - ./config/txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server:ro
      - ./config/Mods:/home/steam/steamcmd/sandstorm/Insurgency/Mods:rw
      - ./config/logs:/home/steam/Steam/logs
    ports:
      - "${PORT}:${PORT}"
      - "${QUERYPORT}:${QUERYPORT}"
```

.env
```
HOSTNAME=[ISMC] MOD MAPS ONLY @120hz
PORT=27015
QUERYPORT=27131
LAUNCH_SERVER_ENV=-MapCycle=MapCycle -Mods ModList=Mods.txt -mutators=ISMCarmory_legacy,ImprovedAI,NoRestrictedArea,ScaleBotAmount,AdvancedSupplyPoints,WelcomeMessage,JoinLeaveMessage,FpLegs,JumpShoot -GameStatsToken=my_token -GameStats -GSLTToken=my_token -ModDownloadTravelTo=TORO?Scenario=Scenario_TORO_Checkpoint_Security
```

Edit: Looking a little closer, this shows up in the application log:

> assert_20231028160852_5.dmp[16]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20231028160852_5.dmp[16]: file ''/tmp/dumps/assert_20231028160852_5.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
