### ISSUE TITLE
TCP ports are absent from docker-compose example in readme

### ISSUE THREAD

**Issue by TheNotary** [AndrewMarchukov/insurgency-sandstorm-server-dockerize#45]
#6 mentions the issue, but it seems there was a regression or something and so the ports aren't specified correctly in the documentation.  

Here's what I'm using for reference:

```
version: '3.7'
services:
  insurgency-sandstorm:
    image: andrewmhub/insurgency-sandstorm:latest
    container_name: insurgency-sandstorm
    restart: unless-stopped
    env_file:
       - .env
    volumes:
      - ./config/ini:/home/steam/steamcmd/sandstorm/Insurgency/Saved/Config/LinuxServer:ro
      - ./config/txt:/home/steam/steamcmd/sandstorm/Insurgency/Config/Server:ro
      - ./config/Mods:/home/steam/steamcmd/sandstorm/Insurgency/Mods:rw
      - ./logs:/home/steam/Steam/logs
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
      - "${QUERYPORT}:${QUERYPORT}/tcp"
      - "${QUERYPORT}:${QUERYPORT}/udp"
```

Notice I'm using relative paths in the volumes section.  It makes the yaml less machine specific, though does assume you're cloning down this repo and creating the docker-compose.yml file there.  

It might be worth creating a `logs/.keep` file along with a copy of the working docker-compose.yml file right here in the repo.  I wind up with so many docker containers running that I lose track what's happening when I don't have them organized into docker-compose.yml files.  

Also, as a side-note, when I connect to this server from the client, I notice I need to specify the port number.  Whereas when I run the server from my local PC, I can get away with simply specifying 127.0.0.1 without providing a port.  Isn't that odd?
